name: GoToProDesign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75823
title: 'GoToProDesign | A Visual Communications Studio | Ready and Creative'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#010101'
    - '#43362e'
    - '#a47692'
    - '#f8f219'
  brandStrength: 0.5625
  lightness: 0.9447166968602687
  saturation: 0.7227973560802639
  rhythmicContrast: 0.8704742933623493
purpose: []
